analyze -sva ./fv_jasper/verilog/BOOM.v ./fv_jasper/verilog/BOOM_mem.v ./fv_jasper/verilog/plusarg_reader.v ./asic/sim/parafuzz.sv

elaborate -top ALUExeUnit_1 -bbox_m StarshipROM

clock clock
reset reset -non_resettable_regs 0


check_spv -create -from {io_brupdate_b1_mispredict_mask io_brupdate_b1_resolve_mask io_fcsr_rm io_get_ftq_pc_entry_cfi_idx_bits io_get_ftq_pc_entry_start_bank io_get_ftq_pc_next_pc io_get_ftq_pc_next_val io_get_ftq_pc_pc io_req_bits_kill io_req_bits_rs1_data io_req_bits_rs2_data io_req_bits_uop_br_mask io_req_bits_uop_br_tag io_req_bits_uop_bypassable io_req_bits_uop_ctrl_br_type io_req_bits_uop_ctrl_csr_cmd io_req_bits_uop_ctrl_fcn_dw io_req_bits_uop_ctrl_imm_sel io_req_bits_uop_ctrl_op1_sel io_req_bits_uop_ctrl_op2_sel io_req_bits_uop_ctrl_op_fcn io_req_bits_uop_dst_rtype io_req_bits_uop_edge_inst io_req_bits_uop_fp_val io_req_bits_uop_ftq_idx io_req_bits_uop_fu_code io_req_bits_uop_imm_packed io_req_bits_uop_is_amo io_req_bits_uop_is_br io_req_bits_uop_is_jal io_req_bits_uop_is_jalr io_req_bits_uop_is_rvc io_req_bits_uop_is_sfb io_req_bits_uop_ldq_idx io_req_bits_uop_pc_lob io_req_bits_uop_pdst io_req_bits_uop_prs1 io_req_bits_uop_rob_idx io_req_bits_uop_stq_idx io_req_bits_uop_taken io_req_bits_uop_uopc io_req_bits_uop_uses_stq} -to {io_brinfo_valid io_bypass_0_valid io_bypass_1_valid io_bypass_2_valid io_iresp_valid io_ll_fresp_bits_fflags_valid io_ll_fresp_valid}
prove -all