analyze -sva ./fv_jasper/verilog/BOOM.v ./fv_jasper/verilog/BOOM_mem.v ./fv_jasper/verilog/plusarg_reader.v ./asic/sim/parafuzz.sv

elaborate -top BoomNonBlockingDCache -bbox_m StarshipROM

clock clock
reset reset -non_resettable_regs 0


check_spv -create -from {auto_out_b_bits_address auto_out_b_bits_param auto_out_b_bits_size auto_out_b_bits_source auto_out_d_bits_data auto_out_d_bits_opcode auto_out_d_bits_param auto_out_d_bits_sink auto_out_d_bits_size auto_out_d_bits_source io_lsu_brupdate_b1_mispredict_mask io_lsu_brupdate_b1_resolve_mask io_lsu_exception io_lsu_force_order io_lsu_req_bits_0_bits_addr io_lsu_req_bits_0_bits_data io_lsu_req_bits_0_bits_is_hella io_lsu_req_bits_0_bits_uop_br_mask io_lsu_req_bits_0_bits_uop_is_amo io_lsu_req_bits_0_bits_uop_ldq_idx io_lsu_req_bits_0_bits_uop_mem_cmd io_lsu_req_bits_0_bits_uop_mem_signed io_lsu_req_bits_0_bits_uop_mem_size io_lsu_req_bits_0_bits_uop_stq_idx io_lsu_req_bits_0_bits_uop_uses_ldq io_lsu_req_bits_0_bits_uop_uses_stq io_lsu_s1_kill_0} -to {auto_out_a_valid auto_out_b_ready auto_out_c_valid auto_out_d_ready auto_out_e_valid io_lsu_nack_0_valid io_lsu_release_valid io_lsu_req_ready io_lsu_resp_0_valid}
prove -all