analyze -sva ./fv_jasper/verilog/BOOM.v ./fv_jasper/verilog/BOOM_mem.v ./fv_jasper/verilog/plusarg_reader.v ./asic/sim/parafuzz.sv

elaborate -top CoherenceManagerWrapper -bbox_m StarshipROM

clock -infer
reset -none -non_resettable_regs 0


check_spv -create -from {auto_coherent_jbar_in_a_bits_address auto_coherent_jbar_in_a_bits_data auto_coherent_jbar_in_a_bits_mask auto_coherent_jbar_in_a_bits_opcode auto_coherent_jbar_in_a_bits_param auto_coherent_jbar_in_a_bits_size auto_coherent_jbar_in_a_bits_source auto_coherent_jbar_in_c_bits_address auto_coherent_jbar_in_c_bits_data auto_coherent_jbar_in_c_bits_opcode auto_coherent_jbar_in_c_bits_param auto_coherent_jbar_in_c_bits_size auto_coherent_jbar_in_c_bits_source auto_coherent_jbar_in_e_bits_sink auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_corrupt auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_data auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_denied auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_opcode auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_param auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_size auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_source} -to {auto_coherent_jbar_in_a_ready auto_coherent_jbar_in_b_valid auto_coherent_jbar_in_c_ready auto_coherent_jbar_in_d_valid auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_valid auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_ready}
prove -all