analyze -sva ./fv_jasper/verilog/BOOM.v ./fv_jasper/verilog/BOOM_mem.v ./fv_jasper/verilog/plusarg_reader.v ./asic/sim/parafuzz.sv

elaborate -top FetchTargetQueue -bbox_m StarshipROM

clock clock
reset reset -non_resettable_regs 0


check_spv -create -from {io_brupdate_b2_mispredict io_brupdate_b2_taken io_brupdate_b2_uop_ftq_idx io_brupdate_b2_uop_pc_lob io_deq_bits io_enq_bits_bpd_meta_0 io_enq_bits_br_mask io_enq_bits_cfi_idx_bits io_enq_bits_cfi_is_call io_enq_bits_cfi_is_ret io_enq_bits_cfi_type io_enq_bits_ghist_current_saw_branch_not_taken io_enq_bits_ghist_new_saw_branch_not_taken io_enq_bits_ghist_new_saw_branch_taken io_enq_bits_ghist_old_history io_enq_bits_ghist_ras_idx io_enq_bits_mask io_enq_bits_pc io_enq_bits_ras_top io_get_ftq_pc_0_ftq_idx io_get_ftq_pc_1_ftq_idx io_redirect_bits} -to {io_bpdupdate_bits_cfi_idx_valid io_bpdupdate_valid io_enq_ready io_get_ftq_pc_0_entry_cfi_idx_valid}
prove -all