analyze -sva ./fv_jasper/verilog/BOOM.v ./fv_jasper/verilog/BOOM_mem.v ./fv_jasper/verilog/plusarg_reader.v ./asic/sim/parafuzz.sv

check_spv -init

elaborate -top StarshipSimTop -bbox_m StarshipROM

clock clock
reset reset -non_resettable_regs 0


get_design_info -module Queue -list input
get_design_info -module Queue -list output
get_design_info -module Queue_1 -list input
get_design_info -module Queue_1 -list output
get_design_info -module TLBuffer -list input
get_design_info -module TLBuffer -list output
get_design_info -module PeripheryBus -list input
get_design_info -module PeripheryBus -list output
get_design_info -module Queue_4 -list input
get_design_info -module Queue_4 -list output
get_design_info -module Queue_5 -list input
get_design_info -module Queue_5 -list output
get_design_info -module TLBuffer_2 -list input
get_design_info -module TLBuffer_2 -list output
get_design_info -module Queue_8 -list input
get_design_info -module Queue_8 -list output
get_design_info -module Queue_9 -list input
get_design_info -module Queue_9 -list output
get_design_info -module AXI4ToTL -list input
get_design_info -module AXI4ToTL -list output
get_design_info -module Queue_10 -list input
get_design_info -module Queue_10 -list output
get_design_info -module AXI4UserYanker -list input
get_design_info -module AXI4UserYanker -list output
get_design_info -module Queue_14 -list input
get_design_info -module Queue_14 -list output
get_design_info -module Queue_16 -list input
get_design_info -module Queue_16 -list output
get_design_info -module AXI4Fragmenter -list input
get_design_info -module AXI4Fragmenter -list output
get_design_info -module TLInterconnectCoupler_5 -list input
get_design_info -module TLInterconnectCoupler_5 -list output
get_design_info -module Queue_17 -list input
get_design_info -module Queue_17 -list output
get_design_info -module Queue_18 -list input
get_design_info -module Queue_18 -list output
get_design_info -module TLBuffer_4 -list input
get_design_info -module TLBuffer_4 -list output
get_design_info -module Queue_19 -list input
get_design_info -module Queue_19 -list output
get_design_info -module TLError -list input
get_design_info -module TLError -list output
get_design_info -module Queue_20 -list input
get_design_info -module Queue_20 -list output
get_design_info -module TLBuffer_5 -list input
get_design_info -module TLBuffer_5 -list output
get_design_info -module ErrorDeviceWrapper -list input
get_design_info -module ErrorDeviceWrapper -list output
get_design_info -module PeripheryBus_1 -list input
get_design_info -module PeripheryBus_1 -list output
get_design_info -module Queue_22 -list input
get_design_info -module Queue_22 -list output
get_design_info -module AXI4UserYanker_1 -list input
get_design_info -module AXI4UserYanker_1 -list output
get_design_info -module Queue_54 -list input
get_design_info -module Queue_54 -list output
get_design_info -module Queue_55 -list input
get_design_info -module Queue_55 -list output
get_design_info -module TLToAXI4 -list input
get_design_info -module TLToAXI4 -list output
get_design_info -module TLInterconnectCoupler_13 -list input
get_design_info -module TLInterconnectCoupler_13 -list output
get_design_info -module MemoryBus -list input
get_design_info -module MemoryBus -list output
get_design_info -module Queue_56 -list input
get_design_info -module Queue_56 -list output
get_design_info -module TLBroadcastTracker -list input
get_design_info -module TLBroadcastTracker -list output
get_design_info -module TLBroadcastTracker_1 -list input
get_design_info -module TLBroadcastTracker_1 -list output
get_design_info -module TLBroadcastTracker_2 -list input
get_design_info -module TLBroadcastTracker_2 -list output
get_design_info -module TLBroadcastTracker_3 -list input
get_design_info -module TLBroadcastTracker_3 -list output
get_design_info -module TLBroadcast -list input
get_design_info -module TLBroadcast -list output
get_design_info -module CoherenceManagerWrapper -list input
get_design_info -module CoherenceManagerWrapper -list output
get_design_info -module BranchKillableQueue -list input
get_design_info -module BranchKillableQueue -list output
get_design_info -module BoomMSHR -list input
get_design_info -module BoomMSHR -list output
get_design_info -module BranchKillableQueue_2 -list input
get_design_info -module BranchKillableQueue_2 -list output
get_design_info -module BoomMSHRFile -list input
get_design_info -module BoomMSHRFile -list output
get_design_info -module L1MetadataArray -list input
get_design_info -module L1MetadataArray -list output
get_design_info -module BoomDuplicatedDataArray -list input
get_design_info -module BoomDuplicatedDataArray -list output
get_design_info -module BoomNonBlockingDCache -list input
get_design_info -module BoomNonBlockingDCache -list output
get_design_info -module ICache -list input
get_design_info -module ICache -list output
get_design_info -module TageTable -list input
get_design_info -module TageTable -list output
get_design_info -module TageTable_1 -list input
get_design_info -module TageTable_1 -list output
get_design_info -module TageTable_2 -list input
get_design_info -module TageTable_2 -list output
get_design_info -module TageTable_3 -list input
get_design_info -module TageTable_3 -list output
get_design_info -module TageTable_4 -list input
get_design_info -module TageTable_4 -list output
get_design_info -module TageTable_5 -list input
get_design_info -module TageTable_5 -list output
get_design_info -module TageBranchPredictorBank -list input
get_design_info -module TageBranchPredictorBank -list output
get_design_info -module BTBBranchPredictorBank -list input
get_design_info -module BTBBranchPredictorBank -list output
get_design_info -module BIMBranchPredictorBank -list input
get_design_info -module BIMBranchPredictorBank -list output
get_design_info -module ComposedBranchPredictorBank -list input
get_design_info -module ComposedBranchPredictorBank -list output
get_design_info -module BranchPredictor -list input
get_design_info -module BranchPredictor -list output
get_design_info -module Queue_60 -list input
get_design_info -module Queue_60 -list output
get_design_info -module Queue_61 -list input
get_design_info -module Queue_61 -list output
get_design_info -module Queue_62 -list input
get_design_info -module Queue_62 -list output
get_design_info -module Queue_63 -list input
get_design_info -module Queue_63 -list output
get_design_info -module FetchTargetQueue -list input
get_design_info -module FetchTargetQueue -list output
get_design_info -module BoomFrontend -list input
get_design_info -module BoomFrontend -list output
get_design_info -module BranchKillableQueue_3 -list input
get_design_info -module BranchKillableQueue_3 -list output
get_design_info -module ALUExeUnit_1 -list input
get_design_info -module ALUExeUnit_1 -list output
get_design_info -module BranchKillableQueue_4 -list input
get_design_info -module BranchKillableQueue_4 -list output
get_design_info -module BranchKillableQueue_5 -list input
get_design_info -module BranchKillableQueue_5 -list output
get_design_info -module FPUExeUnit -list input
get_design_info -module FPUExeUnit -list output
get_design_info -module RegisterFileSynthesizable -list input
get_design_info -module RegisterFileSynthesizable -list output
get_design_info -module FpPipeline -list input
get_design_info -module FpPipeline -list output
get_design_info -module RegisterFileSynthesizable_1 -list input
get_design_info -module RegisterFileSynthesizable_1 -list output
get_design_info -module Rob -list input
get_design_info -module Rob -list output
get_design_info -module BoomCore -list input
get_design_info -module BoomCore -list output
get_design_info -module PTW -list input
get_design_info -module PTW -list output
get_design_info -module BoomTile -list input
get_design_info -module BoomTile -list output
get_design_info -module Queue_64 -list input
get_design_info -module Queue_64 -list output
get_design_info -module Queue_65 -list input
get_design_info -module Queue_65 -list output
get_design_info -module Queue_66 -list input
get_design_info -module Queue_66 -list output
get_design_info -module Queue_67 -list input
get_design_info -module Queue_67 -list output
get_design_info -module Queue_68 -list input
get_design_info -module Queue_68 -list output
get_design_info -module TLBuffer_10 -list input
get_design_info -module TLBuffer_10 -list output
get_design_info -module TilePRCIDomain -list input
get_design_info -module TilePRCIDomain -list output
get_design_info -module Queue_69 -list input
get_design_info -module Queue_69 -list output
get_design_info -module TLPLIC -list input
get_design_info -module TLPLIC -list output
get_design_info -module ClockSinkDomain -list input
get_design_info -module ClockSinkDomain -list output
get_design_info -module Queue_70 -list input
get_design_info -module Queue_70 -list output
get_design_info -module Queue_71 -list input
get_design_info -module Queue_71 -list output
get_design_info -module TLUART -list input
get_design_info -module TLUART -list output
get_design_info -module ClockSinkDomain_2 -list input
get_design_info -module ClockSinkDomain_2 -list output
get_design_info -module StarshipSimTop -list input
get_design_info -module StarshipSimTop -list output
get_design_info -module FAMicroBTBBranchPredictorBank -list input
get_design_info -module FAMicroBTBBranchPredictorBank -list output